server:
  port: 8083

spring:
  application:
    name: transaction-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "juan@@1991"
  flyway:
    enabled: false
  rabbitmq:
    addresses: "amqps://ltqlmrty:c_8BQOD3dksKhM8Gs730tGQZFmf0qPpV@possum.lmq.cloudamqp.com/ltqlmrty"
  level:
    org.springframework.r2dbc: DEBUG
  grpc:
    server:
      port: 9099