server:
  port: ${TRANSACTION_SERVICE_PORT:8083}

spring:
  application:
    name: ${TRANSACTION_SERVICE_NAME:transaction-service}

  r2dbc:
    url: ${TRANSACTION_SERVICE_R2DBC_URL:r2dbc:postgresql://localhost:5432/postgres}
    username: ${TRANSACTION_SERVICE_R2DBC_USERNAME:postgres}
    password: ${TRANSACTION_SERVICE_R2DBC_PASSWORD:''}

  flyway:
    enabled: ${TRANSACTION_SERVICE_FLYWAY_ENABLED:false}

  rabbitmq:
    addresses: ${TRANSACTION_SERVICE_RABBITMQ_ADDRESSES:''}

  level:
    org.springframework.r2dbc: ${TRANSACTION_SERVICE_LOG_R2DBC_LEVEL:DEBUG}

  grpc:
    server:
      port: ${TRANSACTION_SERVICE_GRPC_PORT:9099}
