server:
  port: ${TRANSFER_SERVICE_PORT:8085}

spring:
  application:
    name: ${TRANSFER_SERVICE_NAME:transfer-service}

  r2dbc:
    url: ${TRANSFER_SERVICE_R2DBC_URL:r2dbc:postgresql://localhost:5432/postgres}
    username: ${TRANSFER_SERVICE_R2DBC_USERNAME:postgres}
    password: ${TRANSFER_SERVICE_R2DBC_PASSWORD:''}

  rabbitmq:
    addresses: ${TRANSFER_SERVICE_RABBITMQ_ADDRESSES:''}